version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run: lein deps
      - run:
          name: Ensure No Reflection Warnings
          command: "! lein check 2>&1 | grep 'Reflection warning'"
      - run: lein test
