version: 2.1
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run:
          name: Ensure No Reflection Warnings
          command: "! lein check 2>&1 | grep 'Reflection warning'"
      - run: lein test


workflows:
  workflow:
    jobs:
      - test
